version: "3.9"
services:
  ddc:
    build: .
    image: ddc
    volumes:
      - ./ddc/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  pgadmin:
      image: dpage/pgadmin4
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: fred9702@gmail.com
        PGADMIN_DEFAULT_PASSWORD: root
      restart: always